### ISSUE TITLE
Check the selected processor and target for compatability.

### ISSUE THREAD

**Issue by tl8roy** [knurling-rs/probe-run#115]
After spending an inordinate amount of time trying to work out why RTT wasn't working, I discovered that I had set the wrong target.

As ```probe-run``` knows both the source target (through the path) and the target IC, it should be possible to show a warning if the two aren't compatible with each other.

**Comment by japaric** [comment]
This sounds like a good idea to me. I think we may only be able to implement this in a "best effort" manner though rather than as something with 100% accuracy.

Impl notes from the top of my head:

1. look into the `core_type` field of this `probe_rs::Target`

https://github.com/knurling-rs/probe-run/blob/5fe5ed44e96cf555e5a39f62f87bb11dfb200c00/src/main.rs#L127

2. try to extract the compilation target (e.g. `thumbv6m-none-eabi`) from this path. Note that probe-run can be invoked like this: `probe-run ./my-elf`; in that case there's no target information in the path (the `None` case)

https://github.com/knurling-rs/probe-run/blob/5fe5ed44e96cf555e5a39f62f87bb11dfb200c00/src/main.rs#L122

3. compare (1) and (2) and emit a suggestion or not

- for `M0`, target MUST be `thumbv6m-none-eabi`
- for `M3`, target SHOULD be `thumbv7m-none-eabi`
- for `M4` and `M7`, target SHOULD be `thumbv7em-none-eabi`. (`thumbv7m-none-eabi`  may also be OK but probe-rs has no information about FPU support)
- for `Riscv`, I don't think we can give any suggestion as we don't have any info about instruction set support from probe-rs (I vs IMAC vs IMC)

**Comment by Urhengulas** [comment]
Which compilation should it be in case of `CoreType::Armv8m` which is Cortex M23 M33?
In the "Platform Support" ([link](https://doc.rust-lang.org/nightly/rustc/platform-support.html)) list I can find `thumbv8m.base-none-eabi`, `thumbv8m.main-none-eabi` and `thumbv8m.main-none-eabihf`. Can it be any of them?
