### ISSUE TITLE
probe-run depends on wasmparser

### ISSUE THREAD

**Issue by jonas-schievink** [knurling-rs/probe-run#164]
It seems that we don't turn off enough features of the `object` crate, so it's pulling in a WASM parser. Since we'll never use that, we should remove the dependency.

**Comment by Urhengulas** [comment]
The problem is, that `probe-rs` actually pulls in this dependency with all default features ([see](https://github.com/probe-rs/probe-rs/blob/master/probe-rs/Cargo.toml#L33)).

I've opened https://github.com/probe-rs/probe-rs/issues/559 and asked them to hide the more specific features behind a feature flag.

**Comment by Urhengulas** [comment]
Fixed by #235
