### ISSUE TITLE
probe-run cannot detect pico

### ISSUE THREAD

**Issue by colossalchicken** [knurling-rs/probe-run#409]
**Description**
`probe-run` is unable to detect my **Raspberry Pi Pico**. The pico is visible according to `fdisk`, so it is not a connection or permissions issue. 
**Example**
```
$ probe-run --list-probes

Error: no probe was found.

Common reasons for this are faulty cables or missing permissions.
For detailed instructions, visit: https://github.com/knurling-rs/probe-run#troubleshooting

```

```
$ sudo fdisk -l

...

Disk /dev/sda: 128 MiB, 134217728 bytes, 262144 sectors
Disk model: RP2
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x000a6117
```

**Comment by Urhengulas** [comment]
It might be that you need to update the USB permissions. What is `lsusb` telling you? Refer to https://github.com/knurling-rs/probe-run/#error-no-probe-was-found for more steps.

**Comment by jonathanpallant** [comment]
Because you have shown `fdisk` output, I believe your RP2040 is in USB Bootloader mode. You cannot program an RP2040 in USB Bootloader mode with `probe-run`. Instead you must use a proper ARM SWD Debug Probe, like a SEGGER J-Link or a [Raspberry Pi Debug Probe](https://www.raspberrypi.com/products/debug-probe/).

If you want to upload firmware to the RP2040 in USB Mass Storage mode, try [`elf2uf2`](https://github.com/JoNil/elf2uf2-rs), but then you won't get defmt logging.

**Comment by Urhengulas** [comment]
Thanks @jonathanpallant 
@colossalchicken Does this solve your question?
